### ISSUE TITLE
create chat app modern layout 

### ISSUE THREAD

**Issue by DhruvDabhi1** [DhruvDabhi1/just-for-test#1]
Certainly! Let's break down the tasks needed to create the chat application interface using HTML, CSS, and JavaScript.

Task Breakdown
Project Setup

Create the project folder structure.
Create initial HTML file.
Create CSS stylesheet.
Create JavaScript file.
Basic Layout

Create the HTML structure with two main sections: sidebar and main content area.
Sidebar Implementation

Implement the sidebar with navigation options (Chats, Add New, Games, Updates, Settings).
Add the search bar component at the top of the sidebar.
Add the list of chats/messages with indicators for new messages.
Chat Area Implementation

Implement the chat header with contact name and status.
Implement the chat message area.
Add the message input area with a send button.
Styling

Apply CSS styles to match the design in the provided image.
Ensure responsive design for different screen sizes.
Functionality

Implement chat selection to display messages.
Implement the search functionality to filter chats.
Implement message sending functionality.
Project Setup
Create Project Folder Structure

plaintext
Copy code
```md
chat-app/
├── index.html
├── styles.css
└── script.js
```
Create Initial HTML File (index.html)

html
Copy code
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chat Application</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div class="layout">
        <div class="sidebar">
            <!-- Sidebar content -->
        </div>
        <div class="chat-area">
            <!-- Chat area content -->
        </div>
    </div>
    <script src="script.js"></script>
</body>
</html>
Basic Layout
Update HTML Structure
html
Copy code
<body>
    <div class="layout">
        <div class="sidebar">
            <input type="text" placeholder="Search" class="search-bar">
            <div class="chat-list">
                <!-- List of chats -->
                <div class="chat-item">
                    <span class="chat-name">Ryan Mcleod</span>
                    <span class="chat-time">4:24 pm</span>
                    <span class="chat-unread">3</span>
                </div>
                <!-- Repeat for multiple chats -->
            </div>
            <nav class="nav-menu">
                <ul>
                    <li>Chats</li>
                    <li>Add New</li>
                    <li>Games</li>
                    <li>Updates</li>
                    <li>Settings</li>
                </ul>
            </nav>
        </div>
        <div class="chat-area">
            <header class="chat-header">
                <h2>Ryan Mcleod</h2>
                <span>Online</span>
            </header>
            <div class="messages">
                <!-- Chat messages -->
            </div>
            <footer class="message-input">
                <input type="text" placeholder="Send message">
                <button>Send</button>
            </footer>
        </div>
    </div>
</body>
Sidebar Implementation
Implement Sidebar in HTML
html
Copy code
<div class="sidebar">
    <input type="text" placeholder="Search" class="search-bar">
    <div class="chat-list">
        <div class="chat-item">
            <span class="chat-name">Ryan Mcleod</span>
            <span class="chat-time">4:24 pm</span>
            <span class="chat-unread">3</span>
        </div>
        <!-- Repeat for multiple chats -->
    </div>
    <nav class="nav-menu">
        <ul>
            <li>Chats</li>
            <li>Add New</li>
            <li>Games</li>
            <li>Updates</li>
            <li>Settings</li>
        </ul>
    </nav>
</div>
```
Chat Area Implementation
Implement Chat Area in HTML
html
Copy code
```html
<div class="chat-area">
    <header class="chat-header">
        <h2>Ryan Mcleod</h2>
        <span>Online</span>
    </header>
    <div class="messages">
        <!-- Chat messages -->
    </div>
    <footer class="message-input">
        <input type="text" placeholder="Send message">
        <button>Send</button>
    </footer>
</div>
```
Styling
Add Styles in styles.css
css
Copy code
```css
body {
    margin: 0;
    font-family: Arial, sans-serif;
}

.layout {
    display: flex;
    height: 100vh;
}

.sidebar {
    width: 300px;
    background-color: #f0f0f0;
    padding: 20px;
    display: flex;
    flex-direction: column;
}

.search-bar {
    padding: 10px;
    margin-bottom: 20px;
    border: 1px solid #ccc;
    border-radius: 5px;
}

.chat-list {
    flex-grow: 1;
    overflow-y: auto;
}

.chat-item {
    display: flex;
    justify-content: space-between;
    padding: 10px;
    border-bottom: 1px solid #ccc;
}

.chat-item:hover {
    background-color: #ddd;
    cursor: pointer;
}

.chat-name {
    font-weight: bold;
}

.chat-time {
    color: #888;
}

.chat-unread {
    background-color: #ff0;
    border-radius: 50%;
    padding: 5px;
}

.nav-menu ul {
    list-style: none;
    padding: 0;
}

.nav-menu li {
    margin: 10px 0;
}

.chat-area {
    flex-grow: 1;
    display: flex;
    flex-direction: column;
}

.chat-header {
    padding: 20px;
    border-bottom: 1px solid #ccc;
    display: flex;
    justify-content: space-between;
}

.messages {
    flex-grow: 1;
    padding: 20px;
    overflow-y: auto;
}

.message-input {
    display: flex;
    padding: 10px;
    border-top: 1px solid #ccc;
}

.message-input input {
    flex-grow: 1;
    padding: 10px;
    border: 1px solid #ccc;
    border-radius: 5px;
    margin-right: 10px;
}

.message-input button {
    padding: 10px 20px;
    background-color: #007bff;
    color: #fff;
    border: none;
    border-radius: 5px;
}
```
Functionality
Add JavaScript in script.js
js
Copy code
```js
document.addEventListener('DOMContentLoaded', () => {
    const chatItems = document.querySelectorAll('.chat-item');
    const chatHeader = document.querySelector('.chat-header h2');
    const chatMessages = document.querySelector('.messages');
    const messageInput = document.querySelector('.message-input input');
    const sendButton = document.querySelector('.message-input button');
    const searchBar = document.querySelector('.search-bar');
    const chatList = document.querySelector('.chat-list');

    chatItems.forEach(item => {
        item.addEventListener('click', () => {
            const chatName = item.querySelector('.chat-name').textContent;
            chatHeader.textContent = chatName;
            // Load chat messages (dummy messages for now)
            chatMessages.innerHTML = `
                <div class="message">Hello!</div>
                <div class="message">How are you?</div>
            `;
        });
    });

    sendButton.addEventListener('click', () => {
        const message = messageInput.value;
        if (message.trim() !== '') {
            const newMessage = document.createElement('div');
            newMessage.classList.add('message');
            newMessage.textContent = message;
            chatMessages.appendChild(newMessage);
            messageInput.value = '';
        }
    });

    searchBar.addEventListener('input', () => {
        const filter = searchBar.value.toLowerCase();
        const chatItems = chatList.querySelectorAll('.chat-item');
        chatItems.forEach(item => {
            const chatName = item.querySelector('.chat-name').textContent.toLowerCase();
            if (chatName.includes(filter)) {
                item.style.display = '';
            } else {
                item.style.display = 'none';
            }
        });
    });
});
```
By following these detailed steps, you can create a chat application interface using HTML, CSS, and JavaScript. This includes the project setup, basic layout, sidebar implementation, chat area implementation, styling, and adding interactivity with JavaScript.
